[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 301

[[redirects]]
  from = "/terms-and-conditions"
  to = "/terms-and-conditions.html"
  status = 301
